# -*- coding: utf-8 -*-
"""Copia de Estrada th

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I1culUIg8E3sKN81vtKF6iaJ_1v5iGBj

bu
"""

from IPython.display import HTML, display
import json

# Letra de 'Antes' de C.R.O dividida por versos
versos = [
    "Antes de que te despidas y decidas dejar todo esto en la nada",
    "Antes que finjas amarme y luego me digas que lo nuestro no es nada",
    "Te voy a decir que lo hago solo para ver como brilla esa mirada",
    "pero da igual :("
]

versos_json = json.dumps(versos)

# Crear un cuadro de diálogo HTML con navegación verso por verso
html_code = """
<style>
  @import url('https://fonts.googleapis.com/css2?family=Varela+Round&display=swap');

  @keyframes bounceIn {{
    0% {{ opacity: 0; transform: translate(-50%, -70%) scale(0.8); }}
    70% {{ opacity: 1; transform: translate(-50%, -45%) scale(1.05); }}
    100% {{ opacity: 1; transform: translate(-50%, -50%) scale(1); }}
  }}

  #kittyDialog {{
    animation: bounceIn 0.8s cubic-bezier(0.175, 0.885, 0.32, 1.275) forwards;
    font-family: 'Varela Round', sans-serif;
  }}
</style>

<div id='kittyDialog' style='\n    border: 5px solid #ffb7ce;\n    padding: 25px;\n    background-color: #fff0f5;\n    position: fixed;\n    top: 50%;
    left: 50%;\n    transform: translate(-50%, -50%);\n    z-index: 9999;\n    box-shadow: 0 15px 35px rgba(255, 183, 206, 0.4);\n    border-radius: 30px;\n    width: 650px; /* Increased width */\n    text-align: center;\n'>
  <div style="font-size: 40px; margin-bottom: 10px;">🎀</div>
  <h3 style="margin-top: 0; color: #ff4d88; font-size: 22px;">✨ Antes - C.R.O  ✨</h3>
  <div style="background: white; padding: 15px; border-radius: 20px; border: 2px dashed #ffb7ce; min-height: 100px; display: flex; align-items: center; justify-content: center;">
    <p id='versoText' style="white-space: pre-wrap; color: #ff66a3; font-weight: bold; line-height: 1.6; margin: 0;"></p>
  </div>

  <div style="margin-top: 20px;">
    <button id='nextBtn' onclick="nextVerso()" style='\n        padding: 10px 30px;\n        cursor: pointer;\n        background-color: #ff4d88;\n        color: white;\n        border: none;\n        border-radius: 50px;\n        font-weight: bold;\n        font-size: 16px;\n        transition: transform 0.2s;\n        box-shadow: 0 4px 10px rgba(255, 77, 136, 0.3);\n    ' onmouseover="this.style.transform='scale(1.1)'" onmouseout="this.style.transform='scale(1)'">
      Siguiente ✨
    </button>

    <button id='closeBtn' onclick="document.getElementById('kittyDialog').style.display='none'; document.getElementById('kittyDialog2').style.display='block';" style='\n        display: none;\n        padding: 10px 30px;\n        cursor: pointer;\n        background-color: #ff4d88;\n        color: white;\n        border: none;\n        border-radius: 50px;\n        font-weight: bold;\n        font-size: 16px;\n        transition: transform 0.2s;\n        box-shadow: 0 4px 10px rgba(255, 77, 136, 0.3);\n    ' onmouseover="this.style.transform='scale(1.1)'" onmouseout="this.style.transform='1)'">
      Cerrar 🐾
    </button>
  </div>
</div>

<script>
  (function() {{
    const versos = {versos_json};
    let currentIdx = 0;
    const textElem = document.getElementById('versoText');
    const nextBtn = document.getElementById('nextBtn');
    const closeBtn = document.getElementById('closeBtn');

    window.nextVerso = function() {{
      currentIdx++;
      if (currentIdx < versos.length) {{
        textElem.innerText = versos[currentIdx];
        if (currentIdx === versos.length - 1) {{
           nextBtn.style.display = 'none';
           closeBtn.style.display = 'inline-block';
        }}
      }}
    }};

    // Inicializar primer verso
    textElem.innerText = versos[0];
  }})();
</script>
""".format(versos_json=versos_json)

display(HTML(html_code))


html_code_2 = """
<style>
  @import url('https://fonts.googleapis.com/css2?family=Varela+Round&display=swap');

  @keyframes fadeIn {{
    0% {{ opacity: 0; transform: translate(-50%, -50%) scale(0.9); }}
    100% {{ opacity: 1; transform: translate(-50%, -50%) scale(1); }}
  }}

  #kittyDialog2 {{
    animation: fadeIn 0.8s ease-out forwards;
    font-family: 'Varela Round', sans-serif;
  }}
</style>

<div id='kittyDialog2' style='\n    border: 5px solid #ffb7ce; /* Changed color */\n    padding: 25px; /* Reverted padding to match kittyDialog */\n    background-color: #fff0f5; /* Changed color */\n    position: fixed;\n    top: 50%;\n    left: 50%;\n    transform: translate(-50%, -50%);\n    z-index: 9999;\n    box-shadow: 0 15px 35px rgba(255, 183, 206, 0.4); /* Changed color */\n    border-radius: 30px;\n    width: 650px; /* Increased width */\n    text-align: center;\n    display: none; /* Initially hidden */\n'>
  <div style="font-size: 40px; margin-bottom: 10px;">💖</div>
  <h3 style="margin-top: 0; color: #ff4d88; font-size: 22px;">Thom</h3>
  <div style="background: white; padding: 15px; border-radius: 20px; border: 2px dashed #ffb7ce; /* Changed color */ min-height: 100px; /* Reverted min-height to match kittyDialog */ display: flex; flex-direction: column; align-items: center; justify-content: center;">
    <img src="https://www.gifcen.com/wp-content/uploads/2022/03/hello-kitty-gif.gif" alt="Hello Kitty" style="max-width: 100px; border-radius: 10px; margin-bottom: 10px;">
    <p style="white-space: pre-wrap; color: #ff66a3; font-weight: bold; line-height: 1.6; margin: 0;">te amo mi negro <3</p>
  </div>

  <div style="margin-top: 20px;">
    <button onclick="document.getElementById('kittyDialog2').style.display='none';" style='\n        padding: 10px 30px;\n        cursor: pointer;\n        background-color: #ff4d88; /* Changed color */\n        color: white;\n        border: none;\n        border-radius: 50px;\n        font-weight: bold;\n        font-size: 16px;\n        transition: transform 0.2s;\n        box-shadow: 0 4px 10px rgba(255, 77, 136, 0.3); /* Changed color */\n    ' onmouseover="this.style.transform='scale(1.1)'" onmouseout="this.style.transform='1)'">
      Cerrar 🐾
    </button>
  </div>
</div>
"""

display(HTML(html_code_2))